CREATE DATABASE depot_air_bersih_online;
USE depot_air_bersih_online;

CREATE TABLE tb_admin(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR (100) NOT NULL,
nama_admin VARCHAR (100),
jenis_kelamin ENUM ('','L','P') DEFAULT '',
katasandi VARCHAR (40) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB

CREATE TABLE tb_pembeli(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR (100) NOT NULL,
nama_pembeli VARCHAR (100) NOT NULL,
jenis_kelamin ENUM ('','L','P') DEFAULT '',
UNIQUE(email)
)ENGINE=INNODB

CREATE TABLE tb_depotair(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
jenisair VARCHAR (255) NOT NULL,
jumlah_stok INT (10) NOT NULL,
harga INT (20) NOT NULL,
UNIQUE (jenisair)
)ENGINE=INNODB

CREATE TABLE tb_pemasukanalamat(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
jalan VARCHAR(255) NOT NULL,
kota VARCHAR(255) NOT NULL,
provinsi VARCHAR(255) NOT NULL,
kecamatan VARCHAR(255) NOT NULL,
nomor INT (10) NOT NULL,
rt_rw VARCHAR(255) NOT NULL,
UNIQUE (rt_rw)
)ENGINE=INNODB

CREATE TABLE tb_kontakkami(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
nama VARCHAR (255) NOT NULL,
telp INT (15) NOT NULL,
email VARCHAR (255) NOT NULL,
alamat VARCHAR(255) NOT NULL,
alamat_kantor (255) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB

CREATE TABLE tb_kontak(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
nama VARCHAR (255) NOT NULL,
telp INT (15) NOT NULL,
email VARCHAR (255) NOT NULL,
alamat VARCHAR (255) NOT NULL,
catatan VARCHAR (500) NOT NULL,
UNIQUE(email)
)ENGINE=INNODB

CREATE TABLE tb_pembelian(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
tb_pembeli_id_pembelian INT UNSIGNED,
tb_kontak_id INT UNSIGNED,
tb_pemasukanalamat_id INT UNSIGNED,
jumlah INT (10) NOT NULL,
tgl_beli DATETIME NOT NULL,

FOREIGN KEY (tb_pembeli_id_pembelian) REFERENCES tb_pembeli(id) ON UPDATE CASCADE,
FOREIGN KEY (tb_kontak_id) REFERENCES tb_kontak(id) ON UPDATE CASCADE,
FOREIGN KEY (tb_pemasukanalamat_id) REFERENCES tb_pemasukanalamat(id) ON UPDATE CASCADE
)ENGINE=INNODB;


